### ISSUE TITLE
[NOT AN ISSUE] Thank you for creating this!

### ISSUE THREAD

**Issue by tetreum** [aeroson/mcs-ICodeCompiler#10]
I just had to change 3 lines from my code, to make it work with `mcs-ICodeCompiler`, and now i can build my game for windows with...
# ¡¡MODS SUPPORT!!

Thank you for spending your time to make this and for sharing it for free!
If i ever finish my game, i will send you a key!

**Comment by JakubNei** [comment]
Thank you, glad to hear that.
