### ISSUE TITLE
Error "assemblyString cannot have zero length" + fix

### ISSUE THREAD

**Issue by Arakade** [aeroson/mcs-ICodeCompiler#12]
(firstly, great resource, thanks!)

Just fixed a tiny bug in ScriptBundleLoader that caused the titular bug.
Line 59 (middle of the LINQ in ScriptBundle constructor), switch:
.Where(a => !(a is System.Reflection.Emit.AssemblyBuilder))
to
.Where(a => (!(a is System.Reflection.Emit.AssemblyBuilder) && !string.IsNullOrEmpty(a.Location)))
to remove blanks.
HTH

**Comment by JakubNei** [comment]
Hello, thank you, fixed in: 47372a485ec019958ea52544eba00c935b2b2e4e
