### ISSUE TITLE
Disable updating files

### ISSUE THREAD

**Issue by z3t0** [aeroson/mcs-ICodeCompiler#3]
Hi,

Is it possible to not use Synchronized Invoke and instead just compile the files once at startup?

**Comment by JakubNei** [comment]
First the script is compiled when you click the button.
Then if the script changes synchronized invoke is used to reload the script.
So just remove the parts that use synchronized invoke and compile all scripts in Start() instead of on button click.

**Comment by z3t0** [comment]
Okay I understand. Than you for the explanation.
