### ISSUE TITLE
Non-MonoBehaviour Scripts

### ISSUE THREAD

**Issue by z3t0** [aeroson/mcs-ICodeCompiler#6]
At the moment it seems that only scripts inheriting MonoBehaviour will work successfully, otherwise the constructor will have to be empty. If a script does not inherit MonoBehaviour but has a non-empty constructor then the following error will be thrown in the Unity Console:

The class being tested here is called "Test"

```
MissingMethodException: Method not found: 'Default constructor not found...ctor() of RuntimeCSharpCompiler.Test'.
```

This has something to do with [this](https://github.com/aeroson/mcs-ICodeCompiler/blob/master/example%20Unity3D%20usage/Assets/CSharpCompiler/Demo/DemoLoadScripts.cs#L30) where System.Activator.CreateInstance does not know what to do when trying to instantiate a class that requires arguments in the constructor. 

Do you have any ideas for how to work around this limitation? Currently I am looking into the docs for CreateInstance so I should figure something out soon but was just wondering if you had any thoughts on this.

Thanks!

**Comment by z3t0** [comment]
``` c#
System.Activator.CreateInstance(type, param1, param2, param3 ...)
```

Seems to be work, now just need to find a nice way to integrate this solution in an intuitive way!

**Comment by z3t0** [comment]
Actually, I just realized what should be done is that the System.Activator call should be skipped, and instead if we cannot add the Type to a gameobject, then it should be left because otherwise we just get an error which achieves nothing...

**Comment by JakubNei** [comment]
You could check if the type has parameter less constructor.
Then write error if it has not.
Or you could call the constructor with default values of parameter types. http://stackoverflow.com/questions/325426/programmatic-equivalent-of-defaulttype

Another idea:
You could use dependency injection to automatically fill in correct constructor parameters.
Like I have one instance of InputManager stored in dependency manager, I tell dependency manager to create instance of type T, he sees T has constructor that takes as parameter InputManager and calls this constructor with the stored instance of InputManager.

You can do all of that with reflection. You can use some dependency injection framework such as https://github.com/unitycontainer/unity (this is something different than Unity3D). Or you can make the dependency manager your self, here is some kind of a start: https://gist.github.com/aeroson/d20067cd0c5f8b6b5d0ace607152d810
