### ISSUE TITLE
Support Android platform?

### ISSUE THREAD

**Issue by jeason1997** [aeroson/mcs-ICodeCompiler#8]
I tried it on the Android platform, but it didn't seem to work. I don't know if my usage is wrong. Has anyone been successful?

thank :)

**Comment by jeason1997** [comment]
Sorry, I just found out that I was wrong, Android platform is supported.
Thank you very much for your project, in addition to not supporting enum, near perfect

**Comment by ljn398431** [comment]
I have the same question,could you tell me how to sovle it?
